name: 2027 eval
on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  statuses: write
  contents: read

env:
  PROMPT_ID: d7eb77fe-fb82-4af4-8e02-30219e77eeb5

jobs:
  eval:
    if: "contains(github.event.pull_request.labels.*.name, 'trigger: preview')"
    runs-on: ubuntu-latest
    timeout-minutes: 65
    steps:
      - name: Run 2027 eval
        uses: team2027/evals-action@f9c25786d4e14756afa82bca91fbe0a43cf73ef3
        with:
          api-key: ${{ secrets.EVALS_API_KEY }}
          prompt-id: ${{ env.PROMPT_ID }}
          wait-timeout-minutes: 60
